### ISSUE TITLE
peer review by Xiyan Chen

### ISSUE THREAD

**Issue by siaxiyann** [Isazhou13/Broadway_Gross#3]
Summary:
This paper examines the key factors inclucing the broadway's weekly gross revenue, using multiple linear regression model based on data from Playbill and the Broadway League. It aggregates recent data on key predictors such as ticket pricing, seats capacity and Tony award, showing the result that  ticket pricing, seats capacity, holiday weeks and hotel frequency would positively incluenced the revenue, while Tony award not.

Strong Positive Points:
Strong methods of visualization:
Paper uses effective and various visualizations. Figure 1 used histogram, showing the discription of broadway weekly gross. Figure 3 is scatter plot, showing the gross of a specific week. Every plots is clear and colorful, aligning with the purpose of analysis.

Modeling and Reproducibility:
The authors utilize polling data from playbill and the Broadway League and the dataset appears well-documented. Data cleaning procedures are detailed and clear, enhancing the reproducibility.

The choice of a multiple linear model is a good choice given the need to examine how each factors influence the revenue.

Well-written and Structured Paper:
Paper is well-organized, with a good flow from introduction to data analysis, model explanation, and results discussion. Each section is clearly labeled and cross-referenced. The paper is also well-written with concise and professional language.

Critical Improvements Needed
In Data section, please considering adding tables explaining every variables. It is good to see that there're graphs about each variables, but your paper is too long. so maybe put a table or graph and explain why you think this predictor matters and how this predictor is used in the model.

Suggestions for Improvement:
Considering adding more variables in for a better analysis. For example, the audience demographics or some other variables you're  interested.

Considering shortening your paper. It's already over 20 pages :))

Evaluation:
R is appropriately cited: 1/1
Data are appropriately cited: 1/1
Class paper: 1/1
LLM usage is documented: 1/1
Title: 2/2
Author, date, and repo: 2/2
Abstract: 4/4
Introduction: 4/4
Estimand: 1/1
Data: 10/10
Measurement: 3/4
Model: 10/10
Results: 10/10
Discussion: 10/10
Prose: 6/6
Cross-referaences: 1/1
Captions: 2/2
Graphs/tables/etc: 4/4
Surveys, sampling, and observational data appendix (10/10 pts)
Referencing (4/4 pts)
Commits (2/2 pts)
Sketches (2/2 pts)
Simulation (4/4 pts)
Tests (4/4 pts)
Parquet (1/1 pts)
Reproducible workflow (4/4 pts)
Enhancements (4/4 pts)
Miscellaneous (2/3 pts)
got the mark deduction cuz the paper is a bit too long
Estimated overall mark: 124/126

Other Comments:
Overall, paper is very well-structured and well-written, with effective modeling and strong visualizations. The only suggestions I wanna make is just to make the paper shorter. It's such a strong paper!!

**Comment by Isazhou13** [comment]
Thank you for your review and feedback! I will revise and improve my paper accordingly.
